services:
  - type: web
    name: events-app
    env: node
    buildCommand: ls -la && npm install && (if [ -d "client" ]; then echo "Client directory found" && cd client && npm install && npm run build && cd ..; else echo "Client directory not found"; fi) && (if [ -d "server" ]; then cd server && npm install; fi)
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
