services:
  - type: web
    name: events-app
    env: node
    buildCommand: npm install && (if [ -d "client" ]; then cd client && npm install && npm run build; fi)&& (if [ -d "server" ]; then cd server && npm install; fi)
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
